-- Instrument seed: ~150 standard orchestral/band/chamber instruments,
-- covering the IMSLP/MuseScore canonical list, across all families
-- (brass, woodwind, strings, percussion, keyboard, voice, other).
--
-- UUID choice: `gen_random_uuid()` (pgcrypto, UUIDv4) is used for these
-- static seed rows rather than hand-written v7 literals. Rationale (see
-- also the comment in 0001_extensions.sql): runtime application inserts
-- generate UUIDv7 app-side via the `uuid` crate for time-ordered insert
-- locality on hot, frequently-inserted tables -- that benefit does not
-- apply to a seed migration that runs exactly once and inserts a static,
-- alphabetically-curated batch with no meaningful "creation order" to
-- preserve. `gen_random_uuid()` keeps this migration simple, dependency-free
-- SQL instead of ~150 hand-maintained literals. The column type stays
-- `uuid` either way, so this is invisible to application code.
INSERT INTO instrument (id, key, display_name, aliases, family, transposition, created_at, updated_at) VALUES
-- Woodwind
(gen_random_uuid(), 'piccolo', 'Piccolo', ARRAY['Ottavino'], 'woodwind', NULL, now(), now()),
(gen_random_uuid(), 'flute', 'Flute', ARRAY['Concert Flute', 'Flauto'], 'woodwind', NULL, now(), now()),
(gen_random_uuid(), 'alto_flute', 'Alto Flute', ARRAY[]::text[], 'woodwind', 'G', now(), now()),
(gen_random_uuid(), 'bass_flute', 'Bass Flute', ARRAY[]::text[], 'woodwind', NULL, now(), now()),
(gen_random_uuid(), 'oboe', 'Oboe', ARRAY['Hautbois'], 'woodwind', NULL, now(), now()),
(gen_random_uuid(), 'oboe_da_caccia', 'Oboe da Caccia', ARRAY[]::text[], 'woodwind', NULL, now(), now()),
(gen_random_uuid(), 'english_horn', 'English Horn', ARRAY['Cor Anglais'], 'woodwind', 'F', now(), now()),
(gen_random_uuid(), 'piccolo_oboe', 'Piccolo Oboe', ARRAY['Oboe Musette'], 'woodwind', 'Eb', now(), now()),
(gen_random_uuid(), 'heckelphone', 'Heckelphone', ARRAY['Bass Oboe'], 'woodwind', NULL, now(), now()),
(gen_random_uuid(), 'clarinet_bb', 'Clarinet in B♭', ARRAY['Clarinet'], 'woodwind', 'Bb', now(), now()),
(gen_random_uuid(), 'clarinet_a', 'Clarinet in A', ARRAY[]::text[], 'woodwind', 'A', now(), now()),
(gen_random_uuid(), 'clarinet_eb', 'Clarinet in E♭', ARRAY['Piccolo Clarinet'], 'woodwind', 'Eb', now(), now()),
(gen_random_uuid(), 'clarinet_c', 'Clarinet in C', ARRAY[]::text[], 'woodwind', NULL, now(), now()),
(gen_random_uuid(), 'basset_horn', 'Basset Horn', ARRAY[]::text[], 'woodwind', 'F', now(), now()),
(gen_random_uuid(), 'bass_clarinet', 'Bass Clarinet', ARRAY[]::text[], 'woodwind', 'Bb', now(), now()),
(gen_random_uuid(), 'contrabass_clarinet', 'Contrabass Clarinet', ARRAY[]::text[], 'woodwind', 'Bb', now(), now()),
(gen_random_uuid(), 'bassoon', 'Bassoon', ARRAY['Fagotto'], 'woodwind', NULL, now(), now()),
(gen_random_uuid(), 'contrabassoon', 'Contrabassoon', ARRAY['Double Bassoon'], 'woodwind', NULL, now(), now()),
(gen_random_uuid(), 'soprano_saxophone', 'Soprano Saxophone', ARRAY[]::text[], 'woodwind', 'Bb', now(), now()),
(gen_random_uuid(), 'alto_saxophone', 'Alto Saxophone', ARRAY[]::text[], 'woodwind', 'Eb', now(), now()),
(gen_random_uuid(), 'tenor_saxophone', 'Tenor Saxophone', ARRAY[]::text[], 'woodwind', 'Bb', now(), now()),
(gen_random_uuid(), 'baritone_saxophone', 'Baritone Saxophone', ARRAY[]::text[], 'woodwind', 'Eb', now(), now()),
(gen_random_uuid(), 'bass_saxophone', 'Bass Saxophone', ARRAY[]::text[], 'woodwind', 'Bb', now(), now()),
(gen_random_uuid(), 'sopranino_saxophone', 'Sopranino Saxophone', ARRAY[]::text[], 'woodwind', 'Eb', now(), now()),
(gen_random_uuid(), 'recorder_soprano', 'Soprano Recorder', ARRAY['Descant Recorder'], 'woodwind', NULL, now(), now()),
(gen_random_uuid(), 'recorder_alto', 'Alto Recorder', ARRAY['Treble Recorder'], 'woodwind', NULL, now(), now()),
(gen_random_uuid(), 'recorder_tenor', 'Tenor Recorder', ARRAY[]::text[], 'woodwind', NULL, now(), now()),
(gen_random_uuid(), 'recorder_bass', 'Bass Recorder', ARRAY[]::text[], 'woodwind', NULL, now(), now()),
(gen_random_uuid(), 'penny_whistle', 'Tin Whistle', ARRAY['Penny Whistle'], 'woodwind', NULL, now(), now()),
(gen_random_uuid(), 'bagpipes', 'Bagpipes', ARRAY['Great Highland Bagpipe'], 'woodwind', NULL, now(), now()),
(gen_random_uuid(), 'harmonica', 'Harmonica', ARRAY['Mouth Organ'], 'woodwind', NULL, now(), now()),

-- Brass
(gen_random_uuid(), 'trumpet_bb', 'Trumpet in B♭', ARRAY['Trumpet'], 'brass', 'Bb', now(), now()),
(gen_random_uuid(), 'trumpet_c', 'Trumpet in C', ARRAY[]::text[], 'brass', 'C', now(), now()),
(gen_random_uuid(), 'trumpet_d', 'Trumpet in D', ARRAY[]::text[], 'brass', 'D', now(), now()),
(gen_random_uuid(), 'piccolo_trumpet', 'Piccolo Trumpet', ARRAY[]::text[], 'brass', 'Bb', now(), now()),
(gen_random_uuid(), 'pocket_trumpet', 'Pocket Trumpet', ARRAY[]::text[], 'brass', 'Bb', now(), now()),
(gen_random_uuid(), 'cornet_bb', 'Cornet in B♭', ARRAY['Cornet'], 'brass', 'Bb', now(), now()),
(gen_random_uuid(), 'flugelhorn', 'Flugelhorn', ARRAY[]::text[], 'brass', 'Bb', now(), now()),
(gen_random_uuid(), 'french_horn', 'French Horn', ARRAY['Horn in F', 'Corno'], 'brass', 'F', now(), now()),
(gen_random_uuid(), 'mellophone', 'Mellophone', ARRAY[]::text[], 'brass', 'F', now(), now()),
(gen_random_uuid(), 'trombone', 'Trombone', ARRAY['Tenor Trombone'], 'brass', NULL, now(), now()),
(gen_random_uuid(), 'alto_trombone', 'Alto Trombone', ARRAY[]::text[], 'brass', 'Eb', now(), now()),
(gen_random_uuid(), 'bass_trombone', 'Bass Trombone', ARRAY[]::text[], 'brass', NULL, now(), now()),
(gen_random_uuid(), 'contrabass_trombone', 'Contrabass Trombone', ARRAY[]::text[], 'brass', NULL, now(), now()),
(gen_random_uuid(), 'euphonium', 'Euphonium', ARRAY[]::text[], 'brass', 'Bb', now(), now()),
(gen_random_uuid(), 'baritone_horn', 'Baritone Horn', ARRAY[]::text[], 'brass', 'Bb', now(), now()),
(gen_random_uuid(), 'tuba', 'Tuba', ARRAY[]::text[], 'brass', NULL, now(), now()),
(gen_random_uuid(), 'sousaphone', 'Sousaphone', ARRAY[]::text[], 'brass', NULL, now(), now()),
(gen_random_uuid(), 'wagner_tuba', 'Wagner Tuba', ARRAY[]::text[], 'brass', 'F', now(), now()),
(gen_random_uuid(), 'cimbasso', 'Cimbasso', ARRAY[]::text[], 'brass', NULL, now(), now()),
(gen_random_uuid(), 'alphorn', 'Alphorn', ARRAY[]::text[], 'brass', NULL, now(), now()),
(gen_random_uuid(), 'bugle', 'Bugle', ARRAY[]::text[], 'brass', 'Bb', now(), now()),
(gen_random_uuid(), 'natural_horn', 'Natural Horn', ARRAY[]::text[], 'brass', NULL, now(), now()),
(gen_random_uuid(), 'natural_trumpet', 'Natural Trumpet', ARRAY[]::text[], 'brass', NULL, now(), now()),
(gen_random_uuid(), 'serpent', 'Serpent', ARRAY[]::text[], 'brass', NULL, now(), now()),
(gen_random_uuid(), 'ophicleide', 'Ophicleide', ARRAY[]::text[], 'brass', NULL, now(), now()),

-- Strings
(gen_random_uuid(), 'violin', 'Violin', ARRAY['Violino'], 'strings', NULL, now(), now()),
(gen_random_uuid(), 'viola', 'Viola', ARRAY[]::text[], 'strings', NULL, now(), now()),
(gen_random_uuid(), 'cello', 'Cello', ARRAY['Violoncello'], 'strings', NULL, now(), now()),
(gen_random_uuid(), 'double_bass', 'Double Bass', ARRAY['Contrabass', 'Upright Bass'], 'strings', NULL, now(), now()),
(gen_random_uuid(), 'violone', 'Violone', ARRAY[]::text[], 'strings', NULL, now(), now()),
(gen_random_uuid(), 'viola_da_gamba', 'Viola da Gamba', ARRAY[]::text[], 'strings', NULL, now(), now()),
(gen_random_uuid(), 'viola_d_amore', 'Viola d''Amore', ARRAY[]::text[], 'strings', NULL, now(), now()),
(gen_random_uuid(), 'harp', 'Harp', ARRAY['Arpa'], 'strings', NULL, now(), now()),
(gen_random_uuid(), 'classical_guitar', 'Classical Guitar', ARRAY['Guitar'], 'strings', NULL, now(), now()),
(gen_random_uuid(), 'acoustic_guitar', 'Acoustic Guitar', ARRAY['Steel-String Guitar'], 'strings', NULL, now(), now()),
(gen_random_uuid(), 'electric_guitar', 'Electric Guitar', ARRAY[]::text[], 'strings', NULL, now(), now()),
(gen_random_uuid(), 'bass_guitar', 'Bass Guitar', ARRAY['Electric Bass'], 'strings', NULL, now(), now()),
(gen_random_uuid(), 'banjo', 'Banjo', ARRAY[]::text[], 'strings', NULL, now(), now()),
(gen_random_uuid(), 'mandolin', 'Mandolin', ARRAY[]::text[], 'strings', NULL, now(), now()),
(gen_random_uuid(), 'ukulele', 'Ukulele', ARRAY[]::text[], 'strings', NULL, now(), now()),
(gen_random_uuid(), 'lute', 'Lute', ARRAY[]::text[], 'strings', NULL, now(), now()),
(gen_random_uuid(), 'sitar', 'Sitar', ARRAY[]::text[], 'strings', NULL, now(), now()),
(gen_random_uuid(), 'zither', 'Zither', ARRAY[]::text[], 'strings', NULL, now(), now()),
(gen_random_uuid(), 'autoharp', 'Autoharp', ARRAY[]::text[], 'strings', NULL, now(), now()),
(gen_random_uuid(), 'hurdy_gurdy', 'Hurdy-Gurdy', ARRAY[]::text[], 'strings', NULL, now(), now()),

-- Keyboard
(gen_random_uuid(), 'piano', 'Piano', ARRAY['Pianoforte'], 'keyboard', NULL, now(), now()),
(gen_random_uuid(), 'celesta', 'Celesta', ARRAY[]::text[], 'keyboard', NULL, now(), now()),
(gen_random_uuid(), 'harpsichord', 'Harpsichord', ARRAY['Cembalo'], 'keyboard', NULL, now(), now()),
(gen_random_uuid(), 'clavichord', 'Clavichord', ARRAY[]::text[], 'keyboard', NULL, now(), now()),
(gen_random_uuid(), 'organ', 'Organ', ARRAY['Pipe Organ'], 'keyboard', NULL, now(), now()),
(gen_random_uuid(), 'electric_organ', 'Electric Organ', ARRAY['Hammond Organ'], 'keyboard', NULL, now(), now()),
(gen_random_uuid(), 'accordion', 'Accordion', ARRAY[]::text[], 'keyboard', NULL, now(), now()),
(gen_random_uuid(), 'melodica', 'Melodica', ARRAY[]::text[], 'keyboard', NULL, now(), now()),
(gen_random_uuid(), 'synthesizer', 'Synthesizer', ARRAY[]::text[], 'keyboard', NULL, now(), now()),
(gen_random_uuid(), 'electric_piano', 'Electric Piano', ARRAY['Rhodes Piano'], 'keyboard', NULL, now(), now()),
(gen_random_uuid(), 'fortepiano', 'Fortepiano', ARRAY[]::text[], 'keyboard', NULL, now(), now()),

-- Percussion
(gen_random_uuid(), 'timpani', 'Timpani', ARRAY['Kettle Drums'], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'snare_drum', 'Snare Drum', ARRAY['Side Drum'], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'bass_drum', 'Bass Drum', ARRAY[]::text[], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'tenor_drum', 'Tenor Drum', ARRAY[]::text[], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'bongos', 'Bongos', ARRAY[]::text[], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'congas', 'Congas', ARRAY[]::text[], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'djembe', 'Djembe', ARRAY[]::text[], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'tambourine', 'Tambourine', ARRAY[]::text[], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'triangle', 'Triangle', ARRAY[]::text[], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'cymbals', 'Cymbals', ARRAY['Crash Cymbals'], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'suspended_cymbal', 'Suspended Cymbal', ARRAY[]::text[], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'hi_hat', 'Hi-Hat', ARRAY[]::text[], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'gong', 'Gong', ARRAY['Tam-Tam'], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'glockenspiel', 'Glockenspiel', ARRAY['Orchestra Bells'], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'xylophone', 'Xylophone', ARRAY[]::text[], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'marimba', 'Marimba', ARRAY[]::text[], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'vibraphone', 'Vibraphone', ARRAY['Vibes'], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'chimes', 'Tubular Bells', ARRAY['Chimes'], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'crotales', 'Crotales', ARRAY['Antique Cymbals'], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'castanets', 'Castanets', ARRAY[]::text[], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'maracas', 'Maracas', ARRAY[]::text[], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'claves', 'Claves', ARRAY[]::text[], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'cowbell', 'Cowbell', ARRAY[]::text[], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'woodblock', 'Woodblock', ARRAY[]::text[], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'temple_blocks', 'Temple Blocks', ARRAY[]::text[], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'guiro', 'Guiro', ARRAY[]::text[], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'whip', 'Whip', ARRAY['Slapstick'], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'ratchet', 'Ratchet', ARRAY[]::text[], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'wind_chimes', 'Wind Chimes', ARRAY[]::text[], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'sleigh_bells', 'Sleigh Bells', ARRAY[]::text[], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'anvil', 'Anvil', ARRAY[]::text[], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'steel_drum', 'Steel Drum', ARRAY['Steelpan'], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'timbales', 'Timbales', ARRAY[]::text[], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'drum_kit', 'Drum Kit', ARRAY['Drum Set'], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'tubaphone', 'Flexatone', ARRAY[]::text[], 'percussion', NULL, now(), now()),
(gen_random_uuid(), 'tam_tam', 'Tam-Tam (Large Gong)', ARRAY[]::text[], 'percussion', NULL, now(), now()),

-- Voice
(gen_random_uuid(), 'soprano', 'Soprano', ARRAY[]::text[], 'voice', NULL, now(), now()),
(gen_random_uuid(), 'mezzo_soprano', 'Mezzo-Soprano', ARRAY[]::text[], 'voice', NULL, now(), now()),
(gen_random_uuid(), 'alto_voice', 'Alto', ARRAY['Contralto'], 'voice', NULL, now(), now()),
(gen_random_uuid(), 'countertenor', 'Countertenor', ARRAY[]::text[], 'voice', NULL, now(), now()),
(gen_random_uuid(), 'tenor_voice', 'Tenor', ARRAY[]::text[], 'voice', NULL, now(), now()),
(gen_random_uuid(), 'baritone_voice', 'Baritone', ARRAY[]::text[], 'voice', NULL, now(), now()),
(gen_random_uuid(), 'bass_voice', 'Bass', ARRAY[]::text[], 'voice', NULL, now(), now()),
(gen_random_uuid(), 'treble_voice', 'Treble', ARRAY[]::text[], 'voice', NULL, now(), now()),
(gen_random_uuid(), 'choir', 'Choir (SATB)', ARRAY['SATB Choir'], 'voice', NULL, now(), now()),
(gen_random_uuid(), 'soprano_alto_chorus', 'Soprano/Alto Chorus', ARRAY[]::text[], 'voice', NULL, now(), now()),
(gen_random_uuid(), 'unison_voices', 'Unison Voices', ARRAY[]::text[], 'voice', NULL, now(), now()),
(gen_random_uuid(), 'narrator', 'Narrator', ARRAY['Speaker'], 'voice', NULL, now(), now()),

-- Other / world / electronic / conductor-facing
(gen_random_uuid(), 'conductor', 'Conductor', ARRAY[]::text[], 'other', NULL, now(), now()),
(gen_random_uuid(), 'click_track', 'Click Track', ARRAY[]::text[], 'other', NULL, now(), now()),
(gen_random_uuid(), 'tape', 'Tape / Fixed Media', ARRAY['Backing Track'], 'other', NULL, now(), now()),
(gen_random_uuid(), 'didgeridoo', 'Didgeridoo', ARRAY[]::text[], 'other', NULL, now(), now()),
(gen_random_uuid(), 'theremin', 'Theremin', ARRAY[]::text[], 'other', NULL, now(), now()),
(gen_random_uuid(), 'kalimba', 'Kalimba', ARRAY['Mbira'], 'other', NULL, now(), now()),
(gen_random_uuid(), 'erhu', 'Erhu', ARRAY[]::text[], 'other', NULL, now(), now()),
(gen_random_uuid(), 'shamisen', 'Shamisen', ARRAY[]::text[], 'other', NULL, now(), now()),
(gen_random_uuid(), 'koto', 'Koto', ARRAY[]::text[], 'other', NULL, now(), now()),
(gen_random_uuid(), 'shakuhachi', 'Shakuhachi', ARRAY[]::text[], 'other', NULL, now(), now()),
(gen_random_uuid(), 'duduk', 'Duduk', ARRAY[]::text[], 'other', NULL, now(), now()),
(gen_random_uuid(), 'pan_flute', 'Pan Flute', ARRAY['Panpipes'], 'other', NULL, now(), now()),
(gen_random_uuid(), 'ocarina', 'Ocarina', ARRAY[]::text[], 'other', NULL, now(), now()),
(gen_random_uuid(), 'jaw_harp', 'Jaw Harp', ARRAY['Jew''s Harp'], 'other', NULL, now(), now()),
(gen_random_uuid(), 'glass_harmonica', 'Glass Harmonica', ARRAY[]::text[], 'other', NULL, now(), now()),
(gen_random_uuid(), 'musical_saw', 'Musical Saw', ARRAY[]::text[], 'other', NULL, now(), now()),

-- Additional woodwind/brass/strings to round out coverage toward ~150
(gen_random_uuid(), 'contrabass_flute', 'Contrabass Flute', ARRAY[]::text[], 'woodwind', NULL, now(), now()),
(gen_random_uuid(), 'octobass', 'Octobass', ARRAY[]::text[], 'strings', NULL, now(), now()),
(gen_random_uuid(), 'five_string_double_bass', 'Five-String Double Bass', ARRAY[]::text[], 'strings', NULL, now(), now()),
(gen_random_uuid(), 'piccolo_bass', 'Piccolo Bass', ARRAY[]::text[], 'strings', NULL, now(), now()),
(gen_random_uuid(), 'treble_viol', 'Treble Viol', ARRAY[]::text[], 'strings', NULL, now(), now()),
(gen_random_uuid(), 'tenor_viol', 'Tenor Viol', ARRAY[]::text[], 'strings', NULL, now(), now()),
(gen_random_uuid(), 'bass_viol', 'Bass Viol', ARRAY[]::text[], 'strings', NULL, now(), now()),
(gen_random_uuid(), 'baroque_trumpet', 'Baroque Trumpet', ARRAY[]::text[], 'brass', NULL, now(), now()),
(gen_random_uuid(), 'helicon', 'Helicon', ARRAY[]::text[], 'brass', NULL, now(), now()),
(gen_random_uuid(), 'tenor_horn', 'Tenor Horn', ARRAY['Alto Horn'], 'brass', 'Eb', now(), now()),
(gen_random_uuid(), 'soprano_cornet', 'Soprano Cornet', ARRAY[]::text[], 'brass', 'Eb', now(), now()),
(gen_random_uuid(), 'vienna_horn', 'Vienna Horn', ARRAY[]::text[], 'brass', 'F', now(), now()),
(gen_random_uuid(), 'sarrusophone', 'Sarrusophone', ARRAY[]::text[], 'woodwind', NULL, now(), now()),
(gen_random_uuid(), 'contrabass_saxophone', 'Contrabass Saxophone', ARRAY[]::text[], 'woodwind', 'Eb', now(), now()),
(gen_random_uuid(), 'shawm', 'Shawm', ARRAY[]::text[], 'woodwind', NULL, now(), now()),
(gen_random_uuid(), 'crumhorn', 'Crumhorn', ARRAY[]::text[], 'woodwind', NULL, now(), now()),
(gen_random_uuid(), 'dulcian', 'Dulcian', ARRAY[]::text[], 'woodwind', NULL, now(), now()),
(gen_random_uuid(), 'rackett', 'Rackett', ARRAY[]::text[], 'woodwind', NULL, now(), now()),
(gen_random_uuid(), 'chalumeau', 'Chalumeau', ARRAY[]::text[], 'woodwind', NULL, now(), now()),
(gen_random_uuid(), 'fife', 'Fife', ARRAY[]::text[], 'woodwind', NULL, now(), now()),
(gen_random_uuid(), 'irish_flute', 'Irish Flute', ARRAY[]::text[], 'woodwind', NULL, now(), now()),
(gen_random_uuid(), 'uilleann_pipes', 'Uilleann Pipes', ARRAY[]::text[], 'woodwind', NULL, now(), now()),
(gen_random_uuid(), 'concertina', 'Concertina', ARRAY[]::text[], 'keyboard', NULL, now(), now()),
(gen_random_uuid(), 'bandoneon', 'Bandoneon', ARRAY[]::text[], 'keyboard', NULL, now(), now()),
(gen_random_uuid(), 'reed_organ', 'Reed Organ', ARRAY['Harmonium'], 'keyboard', NULL, now(), now()),
(gen_random_uuid(), 'positive_organ', 'Positive Organ', ARRAY[]::text[], 'keyboard', NULL, now(), now())
;
